import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Cart } from "@/components/cart"; // Import the Cart component
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Simple Header */}
        <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-14 items-center justify-center">
            <div className="flex items-center justify-center w-full space-x-6">
              <Link className="flex items-center space-x-2" href="/">
                <span className="font-bold sm:inline-block">Fapshi SaaS</span>
              </Link>
              <Cart />
            </div>
          </div>
        </header>
        {/* Main Content Area */}
        <main className="flex-grow">{children}</main>
        {/* Simple Footer (Optional) */}
        <footer className="py-6 md:px-8 md:py-0 border-t">
          <div className="container flex flex-col items-center justify-between gap-4 md:h-24 md:flex-row">
            <p className="text-center text-sm leading-loose text-muted-foreground md:text-left">
              Built by Your Name/Company.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
